### ISSUE TITLE
compatibility with Inventory + mod

### ISSUE THREAD

**Issue by drdwing** [VanirDev/VariantEncumbrance#42]
I'm using Inventory + module for bag of holding(Ignore item weight) but activating this module makes the inventory counts the weight of items in the bag. 😢

My environment.
Fvtt v 8.9
Inventory + v0.3.6
Variant encumbrances+midi v0.5.1

**Comment by p4535992** [comment]
Version 0.5.1 or 0.5.11 ?

**Comment by drdwing** [comment]
it's 0.5.1. I'll try again after update.

**Comment by drdwing** [comment]
It still didn't work.

**Comment by p4535992** [comment]
Should be fixed with 0.5.12 , but there is a bug with inventory plus on the "Max Weigth" property. "Ignore Weight" and "Owned Weight" seem to work.

**Comment by drdwing** [comment]
I couldn't update to 0.5.12 😢

**Comment by p4535992** [comment]
Try again Foundry need some minute for sync ?

**Comment by drdwing** [comment]
![Cap 2021-09-04 20-46-28-455](https://user-images.githubusercontent.com/66671688/132093388-af07e05b-3533-418b-a6b1-b28fd827b522.jpg)
![Cap 2021-09-04 20-46-35-395](https://user-images.githubusercontent.com/66671688/132093389-824b127a-3999-4293-8f49-45bcefd1bdd4.jpg)
It doesn't seems to work. Could it be because of inventory +?

**Comment by p4535992** [comment]
what exactly does not work?

The ignore weight feature ? (Tested seem to work)
The inherit weight feature ? (Tested seem to work)
The max weight feature ? (Not work already open a issue on inventory+)
Any exception  on the web console (  "Ctrl + Shitt + I" on browser Chrome) ? 

If you don't know how to do it, pass to me the export json of the character  sheet and i look up the use case.

**Comment by drdwing** [comment]
![Cap 2021-09-04 22-43-00-973](https://user-images.githubusercontent.com/66671688/132096616-9d6072c8-c165-4f99-8900-27977429a49b.jpg)
I think the Ignore weight feature doesn't seem to work. I tried to test using those 4 mods. there isn't any error message in colsole window.

![Cap 2021-09-04 22-51-31-693](https://user-images.githubusercontent.com/66671688/132096776-bebbc66b-9369-4ba9-96e5-ce54602d5c19.jpg)
Even I tried again in the new world, it didn't work. 

fvtt 0.8.9
dnd5e 1.4.2
inventory + 0.3.6
variant encumbrance + midi 0.5.13

**Comment by p4535992** [comment]
Ok it was my fault i tested multiple times, but i never create a "custom" category and then i see the difference should be fixed with version 0.5.14

**Comment by drdwing** [comment]
![Cap 2021-09-05 11-04-41-089](https://user-images.githubusercontent.com/66671688/132112515-2dd75c8c-026c-4060-928e-bda1582e1385.png)
I'm really sorry. Ignore item weight feature still doesn't work. And Foundry displayed those error messages on console window when I dropped a item to new container(applied ignore item weight).

version of variant encumbrance module is 0.5.16.

**Comment by p4535992** [comment]
Tyr out 0.5.18, but i highly recommend avoiding module Inventory Plus (to many check and loss of performance) in favor of the module [Item Collection/Item Containers](https://foundryvtt.com/packages/itemcollection) of you just need a bag of holding.

This is a example with the Bag og Holding premade item of the module

![itemcollection](https://i.imgur.com/zQEMoGB.png)

**Comment by drdwing** [comment]
Thank you!! I don't need to use inventory + only! 👍

**Comment by p4535992** [comment]
is version 0.5.18 work with inventory plus ?

**Comment by drdwing** [comment]
oh, I just checked. Yes it does! Thank you very much!!!!! Thanks for your work!! 👍👍👍👍
