### ISSUE TITLE
Inherent weight miscalculation in Inventory + module

### ISSUE THREAD

**Issue by Dialectikal** [VanirDev/VariantEncumbrance#43]
### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Windows 10
* How Are You Using Foundry: Chrome
* Which Game System: dnd5e
* Modules Enabled?: yes [Inventory+, Item Containers, libWrapper, Variant Encumbrance]

### Issue Description

There is currently a calculation issue with this module and the Inventory+ module.
With Inventory+ there is an Inherent Weight option on each inventory category:

![image](https://user-images.githubusercontent.com/31572084/132772783-af5faf22-b780-443b-98a6-096849343c7d.png)

This option is intended to simulate the weight of a container item which represents that particular category. For instance, if I have a backpack that weighs 30 lbs, then I can set the Inherent Weight equal to 30. This will in turn increase my total carry weight or encumbrance by exactly 30. This is how the property works without the Variant Encumbrance module installed.

![VariantEncumbranceInventoryPlusBug1](https://user-images.githubusercontent.com/31572084/132773467-8700ecd2-e26f-4186-9f1b-212d4d584631.jpg)

By contrast, the Variant Encumbrance module effectively changes this property, setting it to increase by the entered value for every single item contained within that particular category.

![VariantEncumbranceInventoryPlusBug2](https://user-images.githubusercontent.com/31572084/132774215-86cce6f3-9eca-46a7-8c3c-6c650c410007.jpg)

**Comment by p4535992** [comment]
Ty very much for this detailed ticket.
Should be fixed with 0.5.19.
Try it out.

**Comment by Dialectikal** [comment]
There is still a strange calculation going on with this.

Here you can see the Inherent Weight is set to 0:
![VariantEncumbranceInherentWeight1](https://user-images.githubusercontent.com/31572084/132912899-8e7a08f7-3e88-4de3-b743-075b2f5c5340.png)

And here you can see I've increased it by 1:
![VariantEncumbranceInherentWeight2](https://user-images.githubusercontent.com/31572084/132912951-f52d4407-1e10-4fa0-809c-8dc1444c2d0d.png)

This should only increase the total encumbrance by exactly 1, but it appears to be increasing by 3.6.
I can't immediately tell where this value is derived from, but it seems to be multiplied by the items contained within a particular category.

**Comment by VanirDev** [comment]
I've got some suspicions over what this is being caused by in the code, I've made a new branch and asked for clarification from @p4535992 on what some specific elements are intended for to make sure I'm not misunderstanding it. Should be a pretty quick fix once that's cleared up.

**Comment by Dialectikal** [comment]
@p4535992 Just a reminder this is still out there. Wasn't sure if you had seen it.

**Comment by p4535992** [comment]
Try out 0.5.21 and let me know.

**Comment by p4535992** [comment]
it's this error still persist on 0.6.5 version ?

**Comment by p4535992** [comment]
I wil close this issue because i think is solved

**Comment by DanielTheBard** [comment]
Pretty sure it's still not working.

Here is an my player's inventory w/ a backpack category from Inventory+ and the standard weight calculation turned on (it's seemingly correct at 66 lb. outside of ignoring the Inherent Weight value entirely)
![image](https://user-images.githubusercontent.com/4434731/142283138-7c3d7eb5-ab59-49e8-a327-ff225cbe5b81.png)

With your weight calculation turned on (and all the equipped modifiers still set at the default 1), total weight drops by 16 lbs to 50 lbs. Is this intentional behavior? If I adjust the inherent weight by any number, the total moves to reflect by the same amount. If
![image](https://user-images.githubusercontent.com/4434731/142283306-a0bfbec4-6269-4d83-9e12-d6f8e8a4c5f3.png)

Unless I change the Inherent Weight to 0, then it jumps up to 71 lbs. (ironically the correct total weight when including the weight of the backpack)
![image](https://user-images.githubusercontent.com/4434731/142283552-69386bd3-406e-4713-9795-8229f3fb6c2f.png)

If this is intended behavior, some transparency on what's being calculated here would be helpful. I have no multipliers set for if something is equipped or unequipped, but putting items into an Inventory+ category w/ an inherent weight, lowers the total weight. If it has no inherent weight, moving items in/out of the category, has 0 effect on total weight, and instead has added about 5 unaccounted for extra lbs.

**Comment by DanielTheBard** [comment]
That all said, for now, using standard weight calculation w/ auto-application of encumbrance AE+ adding an extra item to account for inherent weight instead, works for my needs. But, if anyone wants the equipped + unequipped modifiers, I think this is still an issue for them.

**Comment by p4535992** [comment]
can you pass me the json of the actor are you using so i can try to replicate the use case ?

**Comment by DanielTheBard** [comment]
[fvtt-Actor-zruggig-widebrain.zip](https://github.com/VanirDev/VariantEncumbrance/files/7558664/fvtt-Actor-zruggig-widebrain.zip)

I think I see what's happening now though. I think the weigh calculation is just taking whatever I put for the inherent weight (other than 0), and ignoring every item's weight in the category, regardless of whether I've checked off the "Ignore Item Weight" button.

**Comment by DanielTheBard** [comment]
Just realized I'd since added a bag of holding category to that sheet once you'd asked for it. (edit: if you delete the items from the bag of holding, it should be the same as what I screenshotted I think)

**Comment by p4535992** [comment]
I "tried" to fix the calculation could you try to do some tests with this zip? TY.
[module.zip](https://github.com/VanirDev/VariantEncumbrance/files/7565784/module.zip)

**Comment by DanielTheBard** [comment]
Alright, after messing around with it, it mostly seems to work, or I can at least work around it. I think this workaround would work regardless of whatever fix you just tried. The extra 5 lbs. when I brought the Inherent Weight to 0 seems to have been from a possibly bugged item, as the unexplainable extra weight went away when I deleted it.

Calculation still seems whack if you have an Inherent Weight for the Inventory+ category and do _not_ have "Ignore Item Weight" enabled. If you do have it enabled, the weight calculation actually all works properly, no matter what Inherent Weight is selected.

So I think the easy way for me to get around this, is what I'd planned before (if not for the bugged item throwing me off): Just set Inherent Weight to 0 for every category. I use the categories for containers, so as long as there's just a copy of the container in their inventory, I can just set the inherent weights to 0 + all the calculation works perfectly 🤷‍♀️

**Comment by p4535992** [comment]
The "Inherent Weight" value, according to the code of inventory plus is added to the value of the total weight https://github.com/syl3r86/inventory-plus/blob/2ae4b759d01498302279dcbd8e899c10dea4b8ea/inventory-plus.js#L473 regardless of whether the "Ignore Weight" flag is set or not if that's the problem I intended?

**Comment by aprusik** [comment]
Was this ever resolved? I see this was changed to "patched" and there is a note saying this isn't compatible with 0.3.5, but Inventory+ is now on 0.4? Even then it seems to still not be calculating weight properly though. Just looking through the repo for this and Inventory+ and trying to piece together what the state of this issue is.

**Comment by p4535992** [comment]
No need to check InventoryPlus the calculation weight is not been changed from 0.3.5 to 0.4.0. 
The weight calculation of the VariantEncumbrance module seem corret to me.
Here inventory plus code:

https://github.com/syl3r86/inventory-plus/blob/38d023a08c60f952b15e125493412349476a1978/inventory-plus.js#L461

```
static calculateWeight(inventory, currency) {
        let customWeight = 0;
        for (let id in inventory) {
            let section = inventory[id];
            => HERE THE IGNORE WEIGHT IF TRUE EVERY ITEM OF THE CATEGORY HAS 0 WEIGHT
            if (section.ignoreWeight !== true) { 
                for (let i of section.items) {
                    console.log(i);
                    customWeight += i.totalWeight;
                }
            }
            =>  HERE THE 'Inherent Weight' IF >0 iIS ADDED EVEN WITH IGNORE WEIGHT TO TRUE
            if (Number(section.ownWeight) > 0) {
                customWeight += Number(section.ownWeight);
            }
        }

        let coinWeight = 0
        if (game.settings.get("dnd5e", "currencyWeight")) {
            let numCoins = Object.values(currency).reduce((val, denom) => val += Math.max(denom, 0), 0);
            if (game.settings.get("dnd5e", "metricWeightUnits")) {
                coinWeight = Math.round((numCoins * 10) / CONFIG.DND5E.encumbrance.currencyPerWeight.metric) / 10;
            } else {
                coinWeight = Math.round((numCoins * 10) / CONFIG.DND5E.encumbrance.currencyPerWeight.imperial) / 10;
            }
        }
        customWeight += coinWeight;

        customWeight = Number(customWeight).toFixed(2);

        return customWeight;
    }
```
**I repeat many people "think" when you check the "ignore weight" the "Inherent Weight" of the category is not calculated**, but the "Inherent Weight" value, according to the code of inventory plus is added to the value of the total weight regardless of whether the "Ignore Weight" flag is set or not.

before picking up the ticket are you sure it's not a problem in this use case?

**Comment by aprusik** [comment]
Yeah, I understand inherent weight is the weight of the container, (i.e. a bag of holding weighs 15 lbs., but its contents are weightless, which is what "ignore weight" applies to.) I agree its a little confusing at first, but it made sense once I wrapped my head around it.

Perhaps the issue I have been able to reproduce is different though. (I can make a separate issue if that's the case) I am not getting _any_ inventory+ category calculation applied to my weight. So inherent weight is not added to the calculated weight, _and_ ignore weight does not ignore the weight of that category's contents.

While I know Javascript, I'm not proficient enough with the Foundry ecosystem to call myself a module developer, and due to this and the small nature of my change I haven't put together a fork/pull request, but I did some digging around in the debugger and made a change on the Varient Encumberance side of things that _seems_ to fix my issue, though I am unsure whether it is fully correct or of its implications elsewhere:

https://github.com/VanirDev/VariantEncumbrance/blob/709eb3b594ca300a1fe208b85b4704159cc42bee/src/module/VariantEncumbranceImpl.ts#L547-L555

Changed to:
```ts
 if ( 
   (item.flags && 
     //@ts-ignore 
     item.flags[VARIANT_ENCUMBRANCE_INVENTORY_PLUS_MODULE_NAME]?.category === categoryId) || 
   //@ts-ignore 
   (item.data?.flags && 
     //@ts-ignore 
     item.data?.flags[VARIANT_ENCUMBRANCE_INVENTORY_PLUS_MODULE_NAME]?.category === categoryId) 
 ) { 
```

I noticed weight was being calculated on a pass where there were no `item.data?.flags` or `item.data?.data?.flags` to grab inventory plus module flags from, but there _was_ `item.flags` to gather the information from, so I reduced the number of data calls in each statement by 1, though adding a third check for just `item.flags` should also work.

**Comment by p4535992** [comment]
ty for the contribution, in all my test i always get the flag from the data property, now you pointed that out, i cannot see on the inventory-plus module a call to the 'setFlag' for that flag and the line of code :

https://github.com/syl3r86/inventory-plus/blob/38d023a08c60f952b15e125493412349476a1978/inventory-plus.js#L444

seems to agree with you, it's an error in my opinion by the developer of inventory-plus, foundry's 'setFlag' and 'getFlag' methods work on the 'data.flags' property not 'flags'.
Your solutions are both valid, for backwards compatibility I add the third check.

Should be fix on the next release and thank you for pointed that out.

**Comment by aprusik** [comment]
No problem! Glad I could be of help.

**Comment by p4535992** [comment]
Well i think this bug is finally fixed, cheers,
