### ISSUE TITLE
[BUG] Item Containers weight calculation with backpacks becomes reverse of intended

### ISSUE THREAD

**Issue by Krigsmaskine** [VanirDev/VariantEncumbrance#47]
**Module Version:** v0.6.8

**Describe the bug**
It seems that this module combined with the newest version of Item Containers (1.8.9) "reverses" when the carrying weight of a bag is calculated. Without this module enabled, I can equip a bag from Item Containers, and the weight is then added and calculated, and when I unequip it, the weight is removed. With the module on, it seems to reverse this?

**To Reproduce**
1. Use the Backpack item from the DnD 5e compendium, have the aforementioned modules enabled.
2. Equip/unequip the bag, notice the weight added doesn't correlate right depending on whether it is equipped or not - for me it added the weight when it was unequipped, rather than equipped.

**Foundry Version:** 
0.8.9

**Game System:** 
DnD 5e 1.5.3

**Comment by p4535992** [comment]
Should be fixed with 0.6.2

**Comment by Krigsmaskine** [comment]
![8nrhcVh2qN](https://user-images.githubusercontent.com/39592771/139519571-39b1b67a-43e6-4528-ad73-1108416f6d55.gif)
I'm still seeing the same behavior, this is with Find the Culprit and only Midi QOL, ItemContainers and VariantEncumbrance on (with dependencies socketlib and the other lib). Backpack goes on, weight goes off.

**Comment by p4535992** [comment]
i think is a retrocompatibility issue is the old backpack you show me? can you try to add a new backpack and tell me if the issue persist ?

**Comment by Krigsmaskine** [comment]
All the backpacks were from the SRD where I changed the sheet, tried and created a new backpack from scratch, issue persists unfortunately
![feyHLhBlOz](https://user-images.githubusercontent.com/39592771/139534981-06b40a0a-ed7e-4145-89b0-912e5300af07.gif)
 
also happens on other characters

**Comment by p4535992** [comment]
Add some more check on 0.6.3  if the error persist export the charater sheet and pass to me for better analyze the use case.

**Comment by Krigsmaskine** [comment]
Thanks for your effort!

The new update made it so the bag's effectively functionless, the weight remains the same whether it is equipped or unequipped, unless I tick on "weightless contents".  Here's the actor data (json saved as a .txt file).

If you want hands on debugging in my world or want more direct contact, you're also free to contact me on Discord at Krigsmaskine#8165.

[fvtt-Actor-jack.txt](https://github.com/VanirDev/VariantEncumbrance/files/7447535/fvtt-Actor-jack.txt)

**Comment by p4535992** [comment]
I don't know what to say with me it works, added more checks and cleaned up the code on version 0.6.4. If that doesn't work for you, pass me the reference to your world on private channel on discord here the username "4535992#1766".
